source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'mysql2'
gem 'rabl'

gem 'haml-rails'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'dynamic_form'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',        group: :doc
gem 'foreigner'
gem 'immigrant'
gem 'validates_email_format_of'
gem 'date_validator'


group :development do
  gem 'byebug'
  gem 'puma'
  gem 'quiet_assets'
  gem 'spring'
end